#!/usr/bin/env ruby
# SPDX-License-Identifier: MIT

# This script generates config.h C header file from .config
# This following instructions are possible in C:
#    if (CONFIG_FOO) { do_something(); }

puts %Q{// This file is automatically generated by #{__FILE__}
// Please do no modify it

#pragma once

#include <stdbool.h>

#define IS_ENABLED(cfg) (cfg) == true

}

while l = STDIN.gets
  if l =~ /^(CONFIG_\w+)=(.*)/
    value = $2
    value = "true" if value == "y"

    puts "#define #{$1} #{value}"
  elsif l =~ /# (CONFIG_\w+) is not set/
    puts "#define #{$1} false"
  end
end
